#!/usr/bin/env node

/**
 * Bundles assets/mochi/mochi-farm.html into src/mochi/mochi-html.ts so the Mochi screen
 * can load it offline in a WebView. Run it again after editing the HTML:
 *   node scripts/sync-mochi.js
 */

const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const html = fs.readFileSync(path.join(root, 'assets/mochi/mochi-farm.html'), 'utf8');
const out = path.join(root, 'src/mochi/mochi-html.ts');

fs.writeFileSync(
  out,
  `// Generated by scripts/sync-mochi.js from assets/mochi/mochi-farm.html. Do not edit by hand.\n` +
    `export const MOCHI_HTML = ${JSON.stringify(html)};\n`
);
console.log(`Wrote ${path.relative(root, out)} (${Math.round(html.length / 1024)} KB)`);
